apiVersion: v1
kind: Service
metadata:
  name: {{ template "datameer.fullname" . }}
  labels:
    app: {{ template "datameer.name" . }}
    chart: {{ template "datameer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8443
      nodePort: 32444
      protocol: TCP
      # This is just the port name and is different from the one defined in
      # deployment.yaml
      name: http
  selector:
    app: {{ template "datameer.name" . }}
    release: {{ .Release.Name }}
